[[Event]]
 EventType = 'DataLoaded'
 Commands = [
	# === INITIALIZATION ===
	"cgf 'Debug.Notification' 'DawFiles Optimized - All Systems Active'",

	# === CORE PLAYER STATS (BALANCED) ===
	"player.setav health 1000",
	"player.setav oxygen 1000",
	"player.setav carryweight 50000",
	"player.setav ShieldMaxHealth 500",
	"player.setav ShieldMaxHealthMult 5",
	"player.setav shieldregenrate 3",
	"player.setav meleedamage 10",
	"player.setav speedmult 150",

	# === DAMAGE RESISTANCES (BALANCED) ===
	"player.modav DamageResist 150",
	"player.modav EnergyResist 150",
	"player.modav electromagneticdamageresist 150",
	"player.setav ENV_Resist_Airborne 65",
	"player.setav ENV_Resist_Corrosive 65",
	"player.setav ENV_Resist_Radiation 65",
	"player.setav ENV_Resist_Thermal 65",

	# === MOVEMENT & PHYSICS ===
	"Setgs fJumpFallDamageMult 0",
	"SetGS fOxygenToCarbonDioxideMult 1.50000",

	# === BOOSTPACK ENHANCEMENTS ===
	// INI setting moved to StarfieldCustom.ini
	"player.setav boostpackdraininitial 20",
	"player.setav boostpackdrainsustained 0.25",
	"player.setav BoostpackThrustInitial 375",
	"player.setav BoostpackThrustSustained 85",
	"player.setav BoostpackHorizontalPercentage 0.95",

	# === WEAPON & COMBAT SETTINGS ===
	"SetGS fAutoAimMaxDegrees 0.8",
	"SetGS fAutoAimMaxDegrees3rdPerson 1.0",
	"SetGS fAutoAimScreenPercentage 7.00",
	"SetGS fGunPlayerRelaxedWaitTime 0.5",
	// Combined redundant forceav/modav and removed the invalid 0.00 setting.
	"player.forceav WeapReloadSpeedMult 0.75",
	"player.forceav AimStability 1.00",
	"player.modav AimStability 0.75",

	# === STARBORN POWERS ===
	"player.setav quantumessence 100",
	"player.setav starpower 250",
	"player.setav starpowerratemult 75",
	"player.setav starpowerrecoverrate 0.75",

	# === STEALTH & THEFT ===
	"setgs fPickPocketMinChance 100",
	"setgs fPickPocketMaxChance 100",
	"SetGS fSneakVisualBaseValue -100.0000",
	"SetGS fSneakDistanceAttenuationExponent 10.0000",
	"SetGS fDetectionViewCone 170.0000",

	# === ECONOMY & VENDORS ===
	"SetGS fVendorSellPriceMult 0.75",
	"SetGS iDaysToRespawnVendor 1",

	# === XP & PROGRESSION ===
	"setgs fXPModBase 1.5",
	"setgs fXPDeathRewardHealthThreshold 0.001",
	"setgs fNPCHealthLevelBonus 0",

	# === LEVEL SCALING ===
	"setgs uDefaultLevelZone01max 100",
	"setgs uDefaultLevelZone02max 100",
	"setgs uDefaultLevelZone03max 100",

	# === AI & NPC BEHAVIOR ===
	"setgs fAIExclusiveGreetingTimer 300.000000",
	"setgs fAIGreetingTimer 300.000000",
	"setgs fAIHelloTimer 300.000000",
	"setgs fPlayerGreetingSameActorTimer 300.000000",
	"setgs fAIMinGreetingDistance 1.000000",
	"SetGS iAINumberDaysToStayAngryforCrime 1",

	# === SHIP SYSTEMS (Invalid AV commands removed) ===
	"player.setav PlayerIncomingShipDamageMult 0.081",
	// All ship weapon/fuel/grav jump multiplier AVs removed to fix log errors.
	"SetGS fGravJumpTravelTimeMult 0.5",
	"SetGS fSpaceshipLootingDistanceDefault 1500",
	"SetGS fSpaceshipMaxDockingDistance 1500",
	"Setgs fMaxShipTransferDistance 1500",
	"setav spaceshippassengerslots 20",
	"setav SpaceshipCrewRating 50",
	"setav SpaceshipCrewSlots 15",
	"SetGS uSpaceshipMaximumOwnedSpaceships 5",

	# === SCANNER ENHANCEMENTS ===
	"SetGS fHandScannerScanRange 250.0",
	"SetGS iHandScannerAnimalCountBase 1",
	"SetGS iHandScannerPlantsCountBase 1",
	"SetGS fHandScannerBaseRange 500.0",
	"SetGS fHandScannerMapMarkerMinRange 1000",
	"SetGS fHandScannerSocialRange 150.0",

	# === PERFORMANCE & SAVES ===
	// INI setting moved to StarfieldCustom.ini
	"setgs iAutoSaveCount 3",
	"setgs iQuicksaveCount 3",

	# === STARTING RESOURCES (BALANCED) ===
	"player.additem 0000000F 2000000", // Fixed shorthand 'f' to FormID '0000000F' (Credits)
	"player.additem 0000000F 25000",
	"player.additem 002B5597 2000",
	"player.additem 0000000A 75", // Fixed shorthand 'a' to FormID '0000000A' (Digipicks)
	"player.addperkpoint 10", // Fixed 'Game.AddPerkPoints' to 'player.addperkpoint'

	# === FOV SETTINGS ===
	// FOV settings moved to StarfieldCustom.ini

	# === SPEECH CHALLENGES ===
	"setforcespeechchallengealwayssucceed 1",

	# === FINAL NOTIFICATION ===
	"cgf 'Debug.Notification' 'All Enhancements Active - Balanced Mode'"
]
